networks:
  traefik-proxy-blumilk-local-environment:
    name: traefik-proxy-blumilk-local-environment

volumes:
  portainer-data-blumilk-local-environment:
    name: portainer-data-blumilk-local-environment

services:
  traefik-proxy-blumilk-local-service:
    image: traefik:v3.3.5
    container_name: traefik-proxy-blumilk-local-environment-container
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.local.environment=true"
      # HTTP
      - "traefik.http.routers.traefik-dashboard-blumilk-local-environment-http-router.rule=Host(`${TRAEFIK_DASHBOARD_HOST_NAME}`)"
      - "traefik.http.routers.traefik-dashboard-blumilk-local-environment-http-router.service=api@internal"
      - "traefik.http.routers.traefik-dashboard-blumilk-local-environment-http-router.entrypoints=web"
      # MIDDLEWARES
#      - "traefik.http.routers.traefik-dashboard-blumilk-local-environment-http-router.middlewares=https-redirect@file"
      # HTTPS
      - "traefik.http.routers.traefik-dashboard-blumilk-local-environment-https-router.rule=Host(`${TRAEFIK_DASHBOARD_HOST_NAME}`)"
      - "traefik.http.routers.traefik-dashboard-blumilk-local-environment-https-router.service=api@internal"
      - "traefik.http.routers.traefik-dashboard-blumilk-local-environment-https-router.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard-blumilk-local-environment-https-router.tls=true"
    networks:
      - traefik-proxy-blumilk-local-environment
    ports:
      # web entrypoint
      - ${TRAEFIK_WEB_ENTRYPOINT_HOST_PORT}:80
      # websecure entrypoint
      - ${TRAEFIK_WEBSECURE_ENTRYPOINT_HOST_PORT}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # static config file
      - ./traefik/config/static/traefik.yml:/etc/traefik/traefik.yml
      # dynamic config directory
      - ./traefik/config/dynamic:/etc/traefik/config/dynamic
      # self-signed certificates
      - ./traefik/certs:/certs

  portainer-blumilk-local-service:
    image: portainer/portainer-ce:lts@sha256:7f10a26bfdda3fc58295ea09b860117ecd86a642d66fb94ce1f27a4c221d4649
    container_name: portainer-blumilk-local-environment-container
    restart: unless-stopped
    command:
      - --admin-password-file
      - /tmp/portainer-admin-password-file
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.local.environment=true"
      # HTTP
      - "traefik.http.routers.portainer-dashboard-blumilk-local-environment-http-router.rule=Host(`${PORTAINER_DASHBOARD_HOST_NAME}`)"
      - "traefik.http.routers.portainer-dashboard-blumilk-local-environment-http-router.entrypoints=web"
      # MIDDLEWARES
      #      - "traefik.http.routers.portainer-dashboard-blumilk-local-environment-http-router.middlewares=https-redirect@file"
      # HTTPS
      - "traefik.http.routers.portainer-dashboard-blumilk-local-environment-https-router.rule=Host(`${PORTAINER_DASHBOARD_HOST_NAME}`)"
      - "traefik.http.routers.portainer-dashboard-blumilk-local-environment-https-router.entrypoints=websecure"
      - "traefik.http.routers.portainer-dashboard-blumilk-local-environment-https-router.tls=true"
      # LOADBALANCER
      - "traefik.http.services.portainer-dashboard-blumilk-local-environment-service.loadbalancer.server.port=9000"
    networks:
      - traefik-proxy-blumilk-local-environment
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data-blumilk-local-environment:/data
      - ./portainer/portainer-admin-password-file:/tmp/portainer-admin-password-file

  bind9:
    container_name: bind-dns
    image: ubuntu/bind9:latest
#    environment:
#      - BIND9_USER=root
#      - TZ=Europe/Warsaw
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "953:953/tcp"
    volumes:
      - ./bind9/config/named.conf.local:/etc/bind/named.conf.local
      - ./bind9/config/named.conf.options:/etc/bind/named.conf.options
      - ./bind9/config/localhost.blumilk.pl.zone:/etc/bind/zones/localhost.blumilk.pl.zone
#      - ./bind9/cache:/var/cache/bind
#      - ./bind9/records:/var/lib/bind
    restart: unless-stopped