http:
    middlewares:

        https-redirect:
            redirectScheme:
                scheme: https
                permanent: true
                port: 443

        response-gzip-compress:
            compress:
                minResponseBodyBytes: 1024
