version: "3.8"

networks:
  traefik-proxy-blumilk-local:
    external: true

services:
  traefik-proxy-blumilk-local-service:
    image: traefik:v2.9.8
    container_name: traefik-proxy-blumilk-local-container
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.environment=true"
      # HTTP
      - "traefik.http.routers.traefik-dashboard-http-router.rule=Host(`${TRAEFIK_DASHBOARD_HOST_NAME}`)"
      - "traefik.http.routers.traefik-dashboard-http-router.service=api@internal"
      - "traefik.http.routers.traefik-dashboard-http-router.entrypoints=web"
      # MIDDLEWARES
#      - "traefik.http.routers.traefik-dashboard-http-router.middlewares=https-redirect@file"
      # HTTPS
      - "traefik.http.routers.traefik-dashboard-https-router.rule=Host(`${TRAEFIK_DASHBOARD_HOST_NAME}`)"
      - "traefik.http.routers.traefik-dashboard-https-router.service=api@internal"
      - "traefik.http.routers.traefik-dashboard-https-router.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard-https-router.tls=true"
    networks:
      - traefik-proxy-blumilk-local
    ports:
      # web entrypoint
      - ${TRAEFIK_WEB_ENTRYPOINT_HOST_PORT}:80
      # websecure entrypoint
      - ${TRAEFIK_WEBSECURE_ENTRYPOINT_HOST_PORT}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # static config file
      - ./config/static/traefik.yaml:/etc/traefik/traefik.yaml
      # dynamic config directory
      - ./config/dynamic:/etc/traefik/config/dynamic
      # self-signed certificates
      - ./certs:/certs
