global:
    checkNewVersion: true
    sendAnonymousUsage: false

log:
    level: DEBUG
    format: common

entryPoints:
    web:
        address: ":80"

    websecure:
        address: ":443"
        http3: {}

api:
    insecure: false
    dashboard: true

providers:
    file:
        directory: "/etc/traefik/config/dynamic"
        watch: true
    docker:
        network: "traefik-proxy-blumilk-local-environment"
        exposedByDefault: false
        constraints: "Label(`traefik.blumilk.local.environment`,`true`)"
